# Generated by Django 5.1.3 on 2024-11-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_books_category_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='kitob',
            field=models.FileField(default='kitob', upload_to='kitob/'),
            preserve_default=False,
        ),
    ]
