# Generated by Django 5.1.3 on 2024-11-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bookreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='kitob',
            field=models.FileField(upload_to='media/'),
        ),
    ]
