# Generated by Django 5.1.3 on 2024-11-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_books_image_alter_books_kitob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aloqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=20)),
                ('mavzu', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
