# Generated by Django 5.1.3 on 2024-12-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aloqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreading',
            name='current_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='books',
            name='toal_pages',
            field=models.IntegerField(default=0),
        ),
    ]
