# Generated by Django 5.1.3 on 2024-12-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bookreading_current_page_books_toal_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreading',
            name='last_read_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
