# Generated by Django 5.1.3 on 2024-12-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bookreading_last_read_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='toal_pages',
            new_name='total_pages',
        ),
    ]
